### ISSUE TITLE
waf error when detecting classic_utility.hpp

### ISSUE THREAD

**Issue by SpotlightKid** [lvtk/ttl2c#2]
I get the following error when running `./waf configure --prefix=/usr`:

```
Setting top to                           : /home/chris/src/arch/aur/ttl2c-git/src/ttl2c 
Setting out to                           : /home/chris/src/arch/aur/ttl2c-git/src/ttl2c/build 
Checking for 'gcc' (C compiler)          : /usr/lib/hardening-wrapper/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/lib/hardening-wrapper/bin/g++ 
Checking for library boost_system        : yes 
Checking for header boost/spirit/include/classic_dynamic.hpp : yes 
Checking for header boost/spirit/include/classic_core.hpp    : yes 
Checking for header boost/spirit/include/classic_parse_tree.hpp : yes 
Checking for header boost/spirit/include/classic_utility.hpp    : not found 
The configuration failed
(complete log in /home/chris/src/arch/aur/ttl2c-git/src/ttl2c/build/config.log)
```

and `config.log` contains:

```
Checking for header boost/spirit/include/classic_utility.hpp
==>
#include <boost/spirit/include/classic_utility.hpp>

int main(int argc, char **argv) {
        (void)argc; (void)argv;
        return 0;
}

<==
[1/2] Compiling ESC[32mbuild/.conf_check_4fde23277467fd62ba8668eb68c1444c/test.cppESC[0m

['/usr/lib/hardening-wrapper/bin/g++', '-DVERSION="1.0.0"', '-DHAVE_BOOST_SPIRIT_INCLUDE_CLASSIC_DYNAMIC_HPP=1', '-DHAVE_BOOST_SPIRIT_INCLUDE_CLASSIC_CORE_HPP=1', '-DHAVE_BOOST_SPIRIT_INCLUDE_CLASSIC_PARSE_TREE_HPP=1', '../test.cpp', '-c', '-o', '/home/chris/src/arch/aur/ttl2c-git/src/ttl2c/build/.conf_check_4fde23277467fd62ba8668eb68c1444c/testbuild/test.cpp.1.o']
[2/2] Linking ESC[33mbuild/.conf_check_4fde23277467fd62ba8668eb68c1444c/testbuild/testprogESC[0m

['/usr/lib/hardening-wrapper/bin/g++', 'test.cpp.1.o', '-o', '/home/chris/src/arch/aur/ttl2c-git/src/ttl2c/build/.conf_check_4fde23277467fd62ba8668eb68c1444c/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']
err: test.cpp.1.o: In function `__static_initialization_and_destruction_0(int, int)':
test.cpp:(.text+0x207): undefined reference to `boost::system::generic_category()'
test.cpp:(.text+0x213): undefined reference to `boost::system::generic_category()'
test.cpp:(.text+0x21f): undefined reference to `boost::system::system_category()'
collect2: Fehler: ld gab 1 als Ende-Status zurück

from /home/chris/src/arch/aur/ttl2c-git/src/ttl2c: Test does not build: Traceback (most recent call last):
  File "/home/chris/src/arch/aur/ttl2c-git/src/ttl2c/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Configure.py", line 335, in run_build
    bld.compile()
  File "/home/chris/src/arch/aur/ttl2c-git/src/ttl2c/.waf3-1.8.17-daa67386b71d29ad7cda321d44eb497a/waflib/Build.py", line 185, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
        {task 140146520591048: cxxprogram test.cpp.1.o -> testprog}
['/usr/lib/hardening-wrapper/bin/g++', 'test.cpp.1.o', '-o', '/home/chris/src/arch/aur/ttl2c-git/src/ttl2c/build/.conf_check_4fde23277467fd62ba8668eb68c1444c/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']

not found
from /home/chris/src/arch/aur/ttl2c-git/src/ttl2c: The configuration failed
```

**Comment by asvetly** [comment]
Also have such one! Can somebody resolve this issue?

**Comment by SpotlightKid** [comment]
As a workaround I do:

```
export LDFLAGS="-lboost_system"
python2 waf configure --prefix=/usr
python2 waf build
```

**Comment by W-Floyd** [comment]
This is also troubling me.
`export LDFLAGS="-lboost_system"` does not make it work either.

Interestingly, it seems that disabling the check for 'boost/spirit/include/classic_utility.hpp' lets it compile correctly.

That is, removing this from wscript
```
conf.check(header_name='boost/spirit/include/classic_utility.hpp',
              uselib_store='BOOST', mandatory=True)
```

**Comment by SpotlightKid** [comment]
I'm now getting a different error for this check:

```
---------------------------------------------------------------
Checking for header boost/spirit/include/classic_utility.hpp
==>
#include <boost/spirit/include/classic_utility.hpp>

int main(int argc, char **argv) {
        (void)argc; (void)argv;
        return 0;
}

<==
[1/2] Compiling ESC[32mbuild/.conf_check_f294e83272b96d2356ef0156052d5b3c/test.cppESC[0m

['/usr/lib/ccache/bin/g++', '-std=c++11', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector', '-D_FORTIFY_SOURCE=2', '-DVERSION="1.0.0"', '-DHAVE_BOOST_SPIRIT_INCLUDE_CLASSIC_DYNAMIC_HPP=1', '-DHAVE_BOOST_SPIRIT_INCLUDE_CLASSIC_CORE_HPP=1', '-DHAVE_BOOST_SPIRIT_INCLUDE_CLASSIC_PARSE_TREE_HPP=1', '../test.cpp', '-c', '-o', '/home/chris/src/arch/aur/ttl2c-git/src/ttl2c/build/.conf_check_f294e83272b96d2356ef0156052d5b3c/testbuild/test.cpp.1.o']
err: In file included from /usr/include/boost/spirit/home/classic/utility.hpp:30:0,
                 from /usr/include/boost/spirit/include/classic_utility.hpp:11,
                 from ../test.cpp:1:
/usr/include/boost/spirit/home/classic/utility/loops.hpp:269:35: error: 'if_' in namespace 'boost::mpl' does not name a template type
             typedef typename mpl::if_<
                                   ^~~
/usr/include/boost/spirit/home/classic/utility/loops.hpp:269:38: error: expected unqualified-id before '<' token
             typedef typename mpl::if_<
                                      ^
```

This seems to be a bug in Boost, akin to this one: https://svn.boost.org/trac/boost/ticket/12052

`classic_utility.hpp` (or one of the headers it includes) should import `if.hpp` but doesn't.

Compilation without the check for `classic_utility.hpp` succeeds because `turtleparser.cpp`, which includes it, also includes `<boost/spirit/include/classic_dynamic.hpp` before, which has the missing import for `if.hpp`.

**Comment by SpotlightKid** [comment]
This has seems to have been fixed in Boost a while ago.
